export { About } from '@/shared/ui/about'
export { Content } from '@/shared/ui/content'
export { Experience } from '@/shared/ui/experience'
export { Header } from '@/shared/ui/header'
export { Projects } from '@/shared/ui/projects'
